import type { INodeProperties } from 'n8n-workflow';

export const automationsOperations: INodeProperties[] = [
        {
                displayName: 'Operation',
                name: 'operation',
                type: 'options',
                noDataExpression: true,
                displayOptions: {
                        show: {
                                resource: ['automations'],
                        },
                },
                options: [
                        {
                                name: 'Trigger Webhook',
                                value: 'triggerWebhook',
                                action: 'Trigger a webhook automation',
                                description: 'Invoke a Level automation webhook by token',
                        },
                ],
                default: 'triggerWebhook',
        },
];

export const automationsFields: INodeProperties[] = [
        {
                displayName: 'Token',
                name: 'token',
                type: 'string',
                required: true,
                default: '',
                typeOptions: {
                        password: true,
                },
                description: 'Webhook token generated by Level for the automation',
                displayOptions: {
                        show: {
                                resource: ['automations'],
                                operation: ['triggerWebhook'],
                        },
                },
        },
        {
                displayName: 'JSON Parameters',
                name: 'jsonParameters',
                type: 'boolean',
                default: false,
                description: 'Whether to define the payload body as JSON or via UI parameters',
                displayOptions: {
                        show: {
                                resource: ['automations'],
                                operation: ['triggerWebhook'],
                        },
                },
        },
        {
                displayName: 'JSON Payload',
                name: 'jsonPayload',
                type: 'json',
                default: '{}',
                description: 'JSON payload to send in the webhook request',
                displayOptions: {
                        show: {
                                resource: ['automations'],
                                operation: ['triggerWebhook'],
                                jsonParameters: [true],
                        },
                },
        },
        {
                displayName: 'Payload',
                name: 'payloadUi',
                type: 'fixedCollection',
                placeholder: 'Add Property',
                default: {},
                options: [
                        {
                                name: 'property',
                                displayName: 'Property',
                                typeOptions: {
                                        multipleValues: true,
                                },
                                values: [
                                        {
                                                displayName: 'Key',
                                                name: 'key',
                                                type: 'string',
                                                default: '',
                                        },
                                        {
                                                displayName: 'Value',
                                                name: 'value',
                                                type: 'string',
                                                default: '',
                                        },
                                ],
                        },
                ],
                displayOptions: {
                        show: {
                                resource: ['automations'],
                                operation: ['triggerWebhook'],
                                jsonParameters: [false],
                        },
                },
                description: 'Key value pairs to include in the webhook payload',
        },
];
