import type { INodeProperties } from 'n8n-workflow';

export const automationOperations: INodeProperties[] = [
        {
                displayName: 'Operation',
                name: 'operation',
                type: 'options',
                noDataExpression: true,
                displayOptions: {
                        show: {
                                resource: ['automation'],
                        },
                },
                options: [
                        {
                                name: 'Trigger Webhook',
                                value: 'triggerWebhook',
                                action: 'Trigger a webhook automation',
                                description: 'Invoke a Level automation webhook by token',
                        },
                ],
                default: 'triggerWebhook',
        },
];

export const automationFields: INodeProperties[] = [
        {
                displayName: 'Webhook Token',
                name: 'token',
                type: 'string',
                required: true,
                default: '',
                typeOptions: {
                        password: true,
                },
                description: 'Token generated by Level for the automation webhook',
                displayOptions: {
                        show: {
                                resource: ['automation'],
                                operation: ['triggerWebhook'],
                        },
                },
        },
        {
                displayName: 'JSON Parameters',
                name: 'jsonParameters',
                type: 'boolean',
                default: false,
                description: 'Whether to define the payload body as JSON or via UI parameters',
                displayOptions: {
                        show: {
                                resource: ['automation'],
                                operation: ['triggerWebhook'],
                        },
                },
        },
        {
                displayName: 'Payload (JSON)',
                name: 'jsonPayload',
                type: 'json',
                default: '{}',
                description: 'JSON payload to send in the webhook request',
                displayOptions: {
                        show: {
                                resource: ['automation'],
                                operation: ['triggerWebhook'],
                                jsonParameters: [true],
                        },
                },
        },
        {
                displayName: 'Device IDs',
                name: 'automationDeviceIds',
                type: 'string',
                typeOptions: {
                        multipleValues: true,
                },
                default: [],
                description: 'Trigger the automation for specific devices (<code>device_ids</code>)',
                displayOptions: {
                        show: {
                                resource: ['automation'],
                                operation: ['triggerWebhook'],
                                jsonParameters: [false],
                        },
                },
        },
        {
                displayName: 'Custom Parameters',
                name: 'automationCustomParameters',
                type: 'fixedCollection',
                placeholder: 'Add Parameter',
                typeOptions: {
                        multipleValues: true,
                },
                default: {},
                description: 'Additional key-value pairs to map to variables configured on the webhook trigger',
                displayOptions: {
                        show: {
                                resource: ['automation'],
                                operation: ['triggerWebhook'],
                                jsonParameters: [false],
                        },
                },
                options: [
                        {
                                displayName: 'Parameter',
                                name: 'parameter',
                                values: [
                                        { displayName: 'Key', name: 'key', type: 'string', default: '' },
                                        { displayName: 'Value', name: 'value', type: 'string', default: '' },
                                ],
                        },
                ],
        },
];
